### ISSUE TITLE
Any way to get the market information

### ISSUE THREAD

**Issue by maquedexiju** [lightninglabs/pool#241]
Hi, I just create an bids order, but I think this order is not accepted yet.

I don't know the reason, and how to make my bid accepted, for example:

* is the amt too high? Or is the interests too low?
* how many asks orders are there? And how to match them better?

In one word, any suggestions to improve the success rate for opening channels?

```
{
                        "details": {
                                "trader_key": "03eb6b43edee4c483683fada5c2417be2321d71522ef1bdc20e719e038d825c60c",
                                "rate_fixed": 496,
                                "amt": "400000",
                                "max_batch_fee_rate_sat_per_kw": "25000",
                                "order_nonce": "91efb8eaef3e3a737b56b0765519a5b75f8cbe05c8a1edde98981fae3697164c",
                                "state": "ORDER_SUBMITTED",
                                "units": 4,
                                "units_unfulfilled": 4,
                                "reserved_value_sat": "66100",
                                "creation_timestamp_ns": "1616748594188860180",
                                "events": [
                                ],
                                "min_units_match": 1
                        },
                        "lease_duration_blocks": 2016,
                        "version": 2,
                        "min_node_tier": "TIER_1"
                }
```

**Comment by guggero** [comment]
There was some info added in https://github.com/lightninglabs/pool/pull/237.
Will be included in the next version.

Also, matchmaking is not an instant process yet since the order book isn't very populated yet.
You only created the order about an hour ago, this usually takes a while. Getting a match also relies on the chain fees which are on the rise again.
Your rate looks a bit low though. You can use the Lightning Terminal to see information about the matching rate of the previous batches too. Or take a look at https://twitter.com/LightningPool (operated by a third party).

**Comment by guggero** [comment]
Closing this since the info we _can_ give is now out there.
